cards = [
	'silver', 
	'gold',
	'premium',
	'club',
	'bonus',
	'bonus digital',
	'sinooil digital',
	'black',
	'easy',
	'для пособий',
	'ironcard',
	'travelcard',
	'картакарта',
	'bccpay',
	'үлкенгекұрмет',
	'travel',
	'blue',
	'diamond',
	'solo',
	'детская',
	'автокарта',
	'экокарта',
	'mastercard world elite',
	'mastercard world bank edition',
	'mastercard world',
	'visa gold',
	'visa infinite',
	'visa signature',
	'visa smart',
	'all in',
	'prisma	infinite',
	'prisma platinum',
	'prisma gold',
	'кредитная',
	'visa virtuon',
	'rbk mini',
	'deposit',
	'invest',
	'freepay',
	'araldy saqta',
	'freedom',
	'araldy saqta premium',
	'премиальная freedom',
	'prestige',
	'премиальная deposit',
	'mastercard gold',
	'nomad club',
	'индивидуал'
]


objectives = [
	['путешествия', 'жд билеты', 'авиа билеты', 'duty free', 'отели', 'транспорт городской', 'туристические достопремечательности', 'круизные линии', 'taxi'],
	['авто', 'азс', 'автосервисы', 'аренда авто'],
	['быт', 'оптика', 'химчистка', 'супермаркеты', 'мебель', 'техника', 'салоны красоты и касметика', 'для детей', 'питомцы', 'одежда', 'обувь', 'дом и ремонт'],
	['еда', 'рестораны', 'кафе', 'доставка еды'],
	['развлечения', 'кино', 'музыка', 'спорт', 'ювелирные изделия', 'фото услуги', 'театры', 'музыкальные', 'бильярд', 'боулинг', 'игровые', 'аквариумы', 'подарки'],
	['онлайн покупки', 'магазин', 'роуминг', 'apple pay', 'sumsung pay', 'google pay', 'музыка', 'геймер', 'apple', 'netflix', 'spotify', 'google', 'интернет магазин', 'markets', 'игровые сервисы', 'онлайн кино', 'онлайн музыка'],
	['образование', 'учеба и развитие', 'книги и канцтовары', 'танцевальные школы', 'фитнес', 'спа', 'обучение'],
	['другое', 'партнёры', 'qr'],
	['здоровье', 'аптеки', 'больницы', 'страхование', 'медицинские услуги'],
	['акции', 'cashback', 'маркет'],
]


banks = {
	'https://guide.kaspi.kz/client/ru/bonus/save/gold/q481': 'Kaspi',
	'https://jusan.kz/en/bonus': 'Jusan',
	'https://halykbank.kz/card/digital': 'HalykBank',
	'https://halykbank.kz/card/dostavka': 'HalykBank',
	'https://halykbank.kz/card/visa-gold-sinooil': 'HalykBank',
	'https://halykbank.kz/card/black': 'HalykBank',
	'https://halykbank.kz/card/diamond': 'HalykBank',
	'https://halykbank.kz/card/easy-digital': 'HalykBank',
	'https://www.bcc.kz/personal/cards/ironcard/': 'BCC',
	'https://www.bcc.kz/personal/cards/travelcard/': 'BCC',
	'https://www.bcc.kz/personal/cards/kartakarta/': 'BCC',
	'https://www.bcc.kz/personal/cards/pension-card/': 'BCC',
	'https://bank.forte.kz/cards/travelcard': 'ForteBank',
	'https://forte.kz/blue': 'ForteBank',
	'https://forte.kz/black': 'ForteBank',
	'https://bank.forte.kz/solo': 'ForteBank',
	'https://forte.kz/kids': 'ForteBank',
	'https://eubank.kz/autocard/': 'EurasianBank',
	'https://eubank.kz/ecocard/': 'EurasianBank',
	'https://eubank.kz/mastercard-gold/': 'EurasianBank',
	'https://eubank.kz/mastercard-world-elite/': 'EurasianBank',
	'https://eubank.kz/visa-gold/': 'EurasianBank',
	'https://eubank.kz/visa-infinite/': 'EurasianBank',
	'https://eubank.kz/mastercard-world-black-edition/': 'EurasianBank',
	'https://eubank.kz/visa-signature/': 'EurasianBank',
	'https://berekebank.kz/ru/personal/cards/allin': 'BerekeBank',
	'https://berekebank.kz/ru/personal/cards/premium': 'BerekeBank',
	'https://bankrbk.kz/ru/individuals/card/debit-cards/visa-signature': 'BankRBK',
	'https://bankrbk.kz/ru/individuals/card/debit-cards/prisma-infinite': 'BankRBK',
	'https://bankrbk.kz/ru/individuals/card/debit-cards/karta-prisma-platinum': 'BankRBK',
	'https://bankrbk.kz/ru/individuals/card/debit-cards/karta-prisma-gold': 'BankRBK',
	'https://bankrbk.kz/ru/individuals/card/cards/credit-card': 'BankRBK',
	'https://bankrbk.kz/ru/individuals/card/debit-cards/visa-virtuon': 'BankRBK',
	'https://www.products.bankrbk.kz/rbkmini-parents': 'BankRBK',
	'https://bankffin.kz/ru/card-issuance/deposit-card': 'FreedomBank',
	'https://bankffin.kz/ru/cards/invest-card/promo': 'FreedomBank',
	'https://bankffin.kz/ru/cards/araldy-saqta/common': 'FreedomBank',
	'https://bankffin.kz/ru/card-issuance/freedom-card': 'FreedomBank',
	'https://bankffin.kz/ru/cards/premium/deposit-card': 'FreedomBank',
	'https://bankffin.kz/ru/cards/premium/prestige-card': 'FreedomBank',
	'https://bankffin.kz/ru/cards/premium/freedom-card': 'FreedomBank',
	'https://bankffin.kz/ru/cards/araldy-saqta/premium': 'FreedomBank'
}
